version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements-dev.txt
    - requirements: doc/requirements-rtd.txt
    - method: setuptools
      path: .

sphinx:
  builder: html
  configuration: doc/conf.py

formats:
  - epub
  - htmlzip
  - pdf
